# Generated by Django 4.2.24 on 2025-09-07 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên phòng')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sức chứa')),
            ],
            options={
                'verbose_name': 'Phòng học',
                'verbose_name_plural': 'Các phòng học',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày dạy')),
                ('period', models.PositiveIntegerField(verbose_name='Tiết học')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.room', verbose_name='Phòng học')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Giáo viên')),
            ],
            options={
                'verbose_name': 'Lịch đăng ký',
                'verbose_name_plural': 'Các lịch đăng ký',
                'ordering': ['date', 'period', 'room'],
                'unique_together': {('room', 'date', 'period')},
            },
        ),
    ]
